"""
keyword_map.py — Multilingual food name → (category, form) mapping dictionary.

Covers ~200 common Indian food items across:
  English, Hindi, Marathi, Tamil, Telugu, Bengali, Gujarati, Kannada, Punjabi, Odia
Plus common transliterations and spelling variants.

Each entry: "food_name_in_any_language" → (display_name, category, form)
"""

FOOD_KEYWORD_MAP = {

    # ─── FRESH PRODUCE — WHOLE ────────────────────────────────────────────────
    # English
    "tomato": ("Tomato", "Fresh Produce", "Whole"),
    "potato": ("Potato", "Fresh Produce", "Whole"),
    "onion": ("Onion", "Fresh Produce", "Whole"),
    "garlic": ("Garlic", "Fresh Produce", "Whole"),
    "ginger": ("Ginger", "Fresh Produce", "Whole"),
    "mango": ("Mango", "Fresh Produce", "Whole"),
    "banana": ("Banana", "Fresh Produce", "Whole"),
    "apple": ("Apple", "Fresh Produce", "Whole"),
    "grapes": ("Grapes", "Fresh Produce", "Whole"),
    "orange": ("Orange", "Fresh Produce", "Whole"),
    "lemon": ("Lemon", "Fresh Produce", "Whole"),
    "lime": ("Lime", "Fresh Produce", "Whole"),
    "spinach": ("Spinach", "Fresh Produce", "Whole"),
    "cabbage": ("Cabbage", "Fresh Produce", "Whole"),
    "cauliflower": ("Cauliflower", "Fresh Produce", "Whole"),
    "brinjal": ("Brinjal / Eggplant", "Fresh Produce", "Whole"),
    "eggplant": ("Eggplant", "Fresh Produce", "Whole"),
    "capsicum": ("Capsicum", "Fresh Produce", "Whole"),
    "cucumber": ("Cucumber", "Fresh Produce", "Whole"),
    "pumpkin": ("Pumpkin", "Fresh Produce", "Whole"),
    "bitter gourd": ("Bitter Gourd", "Fresh Produce", "Whole"),
    "bottle gourd": ("Bottle Gourd", "Fresh Produce", "Whole"),
    "okra": ("Okra / Lady's Finger", "Fresh Produce", "Whole"),
    "ladyfinger": ("Lady's Finger", "Fresh Produce", "Whole"),
    "ladys finger": ("Lady's Finger", "Fresh Produce", "Whole"),
    "peas": ("Peas", "Fresh Produce", "Whole"),
    "beans": ("Beans", "Fresh Produce", "Whole"),
    "carrot": ("Carrot", "Fresh Produce", "Whole"),
    "radish": ("Radish", "Fresh Produce", "Whole"),
    "beetroot": ("Beetroot", "Fresh Produce", "Whole"),
    "sweet potato": ("Sweet Potato", "Fresh Produce", "Whole"),
    "corn": ("Corn / Maize", "Fresh Produce", "Whole"),
    "maize": ("Maize", "Fresh Produce", "Whole"),
    "guava": ("Guava", "Fresh Produce", "Whole"),
    "papaya": ("Papaya", "Fresh Produce", "Whole"),
    "watermelon": ("Watermelon", "Fresh Produce", "Whole"),
    "pomegranate": ("Pomegranate", "Fresh Produce", "Whole"),
    "pineapple": ("Pineapple", "Fresh Produce", "Whole"),
    "coconut": ("Coconut", "Fresh Produce", "Whole"),
    "strawberry": ("Strawberry", "Fresh Produce", "Whole"),
    "fig": ("Fig", "Fresh Produce", "Whole"),
    "jackfruit": ("Jackfruit", "Fresh Produce", "Whole"),
    "drumstick": ("Drumstick", "Fresh Produce", "Whole"),
    "mushroom": ("Mushroom", "Fresh Produce", "Whole"),
    "green chilli": ("Green Chilli", "Fresh Produce", "Whole"),
    "chilli": ("Chilli", "Fresh Produce", "Whole"),
    "coriander": ("Coriander", "Fresh Produce", "Whole"),
    "mint": ("Mint", "Fresh Produce", "Whole"),
    "fenugreek": ("Fenugreek Leaves", "Fresh Produce", "Whole"),

    # Hindi
    "tamatar": ("Tamatar (Tomato)", "Fresh Produce", "Whole"),
    "टमाटर": ("टमाटर", "Fresh Produce", "Whole"),
    "aloo": ("Aloo (Potato)", "Fresh Produce", "Whole"),
    "आलू": ("आलू", "Fresh Produce", "Whole"),
    "pyaz": ("Pyaz (Onion)", "Fresh Produce", "Whole"),
    "pyaaj": ("Pyaaj (Onion)", "Fresh Produce", "Whole"),
    "प्याज": ("प्याज", "Fresh Produce", "Whole"),
    "lehsun": ("Lehsun (Garlic)", "Fresh Produce", "Whole"),
    "लहसुन": ("लहसुन", "Fresh Produce", "Whole"),
    "adrak": ("Adrak (Ginger)", "Fresh Produce", "Whole"),
    "अदरक": ("अदरक", "Fresh Produce", "Whole"),
    "aam": ("Aam (Mango)", "Fresh Produce", "Whole"),
    "आम": ("आम", "Fresh Produce", "Whole"),
    "kela": ("Kela (Banana)", "Fresh Produce", "Whole"),
    "केला": ("केला", "Fresh Produce", "Whole"),
    "seb": ("Seb (Apple)", "Fresh Produce", "Whole"),
    "सेब": ("सेब", "Fresh Produce", "Whole"),
    "angur": ("Angur (Grapes)", "Fresh Produce", "Whole"),
    "अंगूर": ("अंगूर", "Fresh Produce", "Whole"),
    "palak": ("Palak (Spinach)", "Fresh Produce", "Whole"),
    "पालक": ("पालक", "Fresh Produce", "Whole"),
    "patta gobi": ("Patta Gobi (Cabbage)", "Fresh Produce", "Whole"),
    "gobi": ("Gobi (Cauliflower)", "Fresh Produce", "Whole"),
    "गोभी": ("गोभी", "Fresh Produce", "Whole"),
    "baingan": ("Baingan (Brinjal)", "Fresh Produce", "Whole"),
    "बैंगन": ("बैंगन", "Fresh Produce", "Whole"),
    "shimla mirch": ("Shimla Mirch (Capsicum)", "Fresh Produce", "Whole"),
    "kheera": ("Kheera (Cucumber)", "Fresh Produce", "Whole"),
    "खीरा": ("खीरा", "Fresh Produce", "Whole"),
    "kaddu": ("Kaddu (Pumpkin)", "Fresh Produce", "Whole"),
    "karela": ("Karela (Bitter Gourd)", "Fresh Produce", "Whole"),
    "करेला": ("करेला", "Fresh Produce", "Whole"),
    "lauki": ("Lauki (Bottle Gourd)", "Fresh Produce", "Whole"),
    "bhindi": ("Bhindi (Okra)", "Fresh Produce", "Whole"),
    "भिंडी": ("भिंडी", "Fresh Produce", "Whole"),
    "matar": ("Matar (Peas)", "Fresh Produce", "Whole"),
    "मटर": ("मटर", "Fresh Produce", "Whole"),
    "gajar": ("Gajar (Carrot)", "Fresh Produce", "Whole"),
    "गाजर": ("गाजर", "Fresh Produce", "Whole"),
    "mooli": ("Mooli (Radish)", "Fresh Produce", "Whole"),
    "amrud": ("Amrud (Guava)", "Fresh Produce", "Whole"),
    "papita": ("Papita (Papaya)", "Fresh Produce", "Whole"),
    "तरबूज": ("Tarbuz (Watermelon)", "Fresh Produce", "Whole"),
    "anaar": ("Anaar (Pomegranate)", "Fresh Produce", "Whole"),
    "अनार": ("अनार", "Fresh Produce", "Whole"),
    "nariyal": ("Nariyal (Coconut)", "Fresh Produce", "Whole"),
    "नारियल": ("नारियल", "Fresh Produce", "Whole"),
    "mirch": ("Mirch (Chilli)", "Fresh Produce", "Whole"),
    "मिर्च": ("मिर्च", "Fresh Produce", "Whole"),
    "dhaniya": ("Dhaniya (Coriander)", "Fresh Produce", "Whole"),
    "धनिया": ("धनिया", "Fresh Produce", "Whole"),
    "pudina": ("Pudina (Mint)", "Fresh Produce", "Whole"),
    "पुदीना": ("पुदीना", "Fresh Produce", "Whole"),
    "methi": ("Methi (Fenugreek)", "Fresh Produce", "Whole"),
    "मेथी": ("मेथी", "Fresh Produce", "Whole"),

    # Tamil
    "thakkali": ("Thakkali (Tomato)", "Fresh Produce", "Whole"),
    "தக்காளி": ("தக்காளி", "Fresh Produce", "Whole"),
    "urulaikizhangu": ("Urulaikizhangu (Potato)", "Fresh Produce", "Whole"),
    "vengayam": ("Vengayam (Onion)", "Fresh Produce", "Whole"),
    "வெங்காயம்": ("வெங்காயம்", "Fresh Produce", "Whole"),
    "mangai": ("Mangai (Mango)", "Fresh Produce", "Whole"),
    "மாம்பழம்": ("மாம்பழம்", "Fresh Produce", "Whole"),
    "vazhaipazham": ("Vazhaipazham (Banana)", "Fresh Produce", "Whole"),
    "வாழைப்பழம்": ("வாழைப்பழம்", "Fresh Produce", "Whole"),
    "keerai": ("Keerai (Spinach)", "Fresh Produce", "Whole"),
    "கீரை": ("கீரை", "Fresh Produce", "Whole"),
    "kathirikkai": ("Kathirikkai (Brinjal)", "Fresh Produce", "Whole"),
    "vendaikkai": ("Vendaikkai (Okra)", "Fresh Produce", "Whole"),
    "வெண்டைக்காய்": ("வெண்டைக்காய்", "Fresh Produce", "Whole"),

    # Telugu
    "tomato": ("Tomato", "Fresh Produce", "Whole"),
    "vankaya": ("Vankaya (Brinjal)", "Fresh Produce", "Whole"),
    "bendakaya": ("Bendakaya (Okra)", "Fresh Produce", "Whole"),
    "బెండకాయ": ("బెండకాయ", "Fresh Produce", "Whole"),
    "allam": ("Allam (Ginger)", "Fresh Produce", "Whole"),
    "అల్లం": ("అల్లం", "Fresh Produce", "Whole"),

    # Bengali
    "aam": ("Aam (Mango)", "Fresh Produce", "Whole"),
    "আম": ("আম", "Fresh Produce", "Whole"),
    "kola": ("Kola (Banana)", "Fresh Produce", "Whole"),
    "কলা": ("কলা", "Fresh Produce", "Whole"),
    "begun": ("Begun (Brinjal)", "Fresh Produce", "Whole"),
    "বেগুন": ("বেগুন", "Fresh Produce", "Whole"),
    "potol": ("Potol (Pointed Gourd)", "Fresh Produce", "Whole"),
    "আলু": ("Aloo (Potato)", "Fresh Produce", "Whole"),

    # Marathi
    "tomato": ("Tomato", "Fresh Produce", "Whole"),
    "vaangi": ("Vaangi (Brinjal)", "Fresh Produce", "Whole"),
    "bhendi": ("Bhendi (Okra)", "Fresh Produce", "Whole"),
    "आंबा": ("Amba (Mango)", "Fresh Produce", "Whole"),
    "kanda": ("Kanda (Onion)", "Fresh Produce", "Whole"),
    "कांदा": ("कांदा", "Fresh Produce", "Whole"),

    # Gujarati
    "ringan": ("Ringan (Brinjal)", "Fresh Produce", "Whole"),
    "रींगण": ("Ringan", "Fresh Produce", "Whole"),
    "keri": ("Keri (Mango)", "Fresh Produce", "Whole"),
    "કેરી": ("કેરી", "Fresh Produce", "Whole"),
    "dungri": ("Dungri (Onion)", "Fresh Produce", "Whole"),
    "ડુંગળી": ("ડુંગળી", "Fresh Produce", "Whole"),

    # Kannada
    "gullibadanekai": ("Gullibadanekai (Brinjal)", "Fresh Produce", "Whole"),
    "bende": ("Bende (Okra)", "Fresh Produce", "Whole"),
    "ಬೆಂಡೆ": ("ಬೆಂಡೆ", "Fresh Produce", "Whole"),
    "ಮಾವು": ("Maavu (Mango)", "Fresh Produce", "Whole"),

    # Punjabi
    "tamatar": ("Tamatar (Tomato)", "Fresh Produce", "Whole"),
    "ਟਮਾਟਰ": ("ਟਮਾਟਰ", "Fresh Produce", "Whole"),
    "aam": ("Aam (Mango)", "Fresh Produce", "Whole"),
    "ਅੰਬ": ("ਅੰਬ", "Fresh Produce", "Whole"),
    "pyaz": ("Pyaz (Onion)", "Fresh Produce", "Whole"),
    "ਪਿਆਜ਼": ("ਪਿਆਜ਼", "Fresh Produce", "Whole"),

    # ─── FRESH PRODUCE — CUT/PROCESSED ───────────────────────────────────────
    "sliced mango": ("Sliced Mango", "Fresh Produce", "Cut/Processed"),
    "cut fruit": ("Cut Fruit", "Fresh Produce", "Cut/Processed"),
    "cut vegetable": ("Cut Vegetable", "Fresh Produce", "Cut/Processed"),
    "chopped onion": ("Chopped Onion", "Fresh Produce", "Cut/Processed"),
    "sliced tomato": ("Sliced Tomato", "Fresh Produce", "Cut/Processed"),
    "fresh salad": ("Fresh Salad", "Fresh Produce", "Cut/Processed"),
    "kata hua aam": ("Cut Mango", "Fresh Produce", "Cut/Processed"),
    "kata hua sabzi": ("Cut Vegetables", "Fresh Produce", "Cut/Processed"),
    "कटा आम": ("कटा आम", "Fresh Produce", "Cut/Processed"),
    "कटी सब्जी": ("कटी सब्जी", "Fresh Produce", "Cut/Processed"),

    # ─── DAIRY — LIQUID ───────────────────────────────────────────────────────
    "milk": ("Milk", "Dairy", "Liquid"),
    "curd": ("Curd / Yogurt", "Dairy", "Liquid"),
    "yogurt": ("Yogurt", "Dairy", "Liquid"),
    "lassi": ("Lassi", "Dairy", "Liquid"),
    "buttermilk": ("Buttermilk", "Dairy", "Liquid"),
    "ghee": ("Ghee", "Dairy", "Liquid"),
    "cream": ("Cream", "Dairy", "Liquid"),
    "condensed milk": ("Condensed Milk", "Dairy", "Liquid"),
    # Hindi
    "doodh": ("Doodh (Milk)", "Dairy", "Liquid"),
    "दूध": ("दूध", "Dairy", "Liquid"),
    "dahi": ("Dahi (Curd)", "Dairy", "Liquid"),
    "दही": ("दही", "Dairy", "Liquid"),
    "ghee": ("Ghee", "Dairy", "Liquid"),
    "घी": ("घी", "Dairy", "Liquid"),
    "chaach": ("Chaach (Buttermilk)", "Dairy", "Liquid"),
    "छाछ": ("छाछ", "Dairy", "Liquid"),
    "makkhan": ("Makkhan (Butter)", "Dairy", "Liquid"),
    "मक्खन": ("मक्खन", "Dairy", "Liquid"),
    # Tamil
    "paal": ("Paal (Milk)", "Dairy", "Liquid"),
    "பால்": ("பால்", "Dairy", "Liquid"),
    "thayir": ("Thayir (Curd)", "Dairy", "Liquid"),
    "தயிர்": ("தயிர்", "Dairy", "Liquid"),
    "nei": ("Nei (Ghee)", "Dairy", "Liquid"),
    # Bengali
    "dudh": ("Dudh (Milk)", "Dairy", "Liquid"),
    "দুধ": ("দুধ", "Dairy", "Liquid"),
    "doi": ("Doi (Curd)", "Dairy", "Liquid"),
    "দই": ("দই", "Dairy", "Liquid"),
    # Marathi
    "dudh": ("Dudh (Milk)", "Dairy", "Liquid"),
    "दूध": ("दूध", "Dairy", "Liquid"),
    # Gujarati
    "dudh": ("Dudh (Milk)", "Dairy", "Liquid"),
    "દૂધ": ("દૂધ", "Dairy", "Liquid"),
    "dahi": ("Dahi (Curd)", "Dairy", "Liquid"),
    "દહીં": ("દહીં", "Dairy", "Liquid"),
    # Kannada
    "haalu": ("Haalu (Milk)", "Dairy", "Liquid"),
    "ಹಾಲು": ("ಹಾಲು", "Dairy", "Liquid"),
    "mosaru": ("Mosaru (Curd)", "Dairy", "Liquid"),
    "ಮೊಸರು": ("ಮೊಸರು", "Dairy", "Liquid"),
    # Telugu
    "paalu": ("Paalu (Milk)", "Dairy", "Liquid"),
    "పాలు": ("పాలు", "Dairy", "Liquid"),
    "perugu": ("Perugu (Curd)", "Dairy", "Liquid"),
    "పెరుగు": ("పెరుగు", "Dairy", "Liquid"),
    # Punjabi
    "dudh": ("Dudh (Milk)", "Dairy", "Liquid"),
    "ਦੁੱਧ": ("ਦੁੱਧ", "Dairy", "Liquid"),

    # ─── DAIRY — WHOLE (SOLID) ────────────────────────────────────────────────
    "paneer": ("Paneer", "Dairy", "Whole"),
    "पनीर": ("पनीर", "Dairy", "Whole"),
    "cheese": ("Cheese", "Dairy", "Whole"),
    "butter": ("Butter", "Dairy", "Whole"),
    "mawa": ("Mawa / Khoya", "Dairy", "Whole"),
    "khoya": ("Khoya", "Dairy", "Whole"),
    "खोया": ("खोया", "Dairy", "Whole"),
    "चीज़": ("Cheese", "Dairy", "Whole"),
    # Tamil
    "paneer": ("Paneer", "Dairy", "Whole"),
    # Telugu
    "paneer": ("Paneer", "Dairy", "Whole"),

    # ─── DRY SNACKS — POWDER ─────────────────────────────────────────────────
    "rice flour": ("Rice Flour", "Dry Snacks", "Powder"),
    "wheat flour": ("Wheat Flour", "Dry Snacks", "Powder"),
    "flour": ("Flour / Atta", "Dry Snacks", "Powder"),
    "besan": ("Besan (Gram Flour)", "Dry Snacks", "Powder"),
    "बेसन": ("बेसन", "Dry Snacks", "Powder"),
    "atta": ("Atta (Wheat Flour)", "Dry Snacks", "Powder"),
    "आटा": ("आटा", "Dry Snacks", "Powder"),
    "maida": ("Maida (Refined Flour)", "Dry Snacks", "Powder"),
    "मैदा": ("मैदा", "Dry Snacks", "Powder"),
    "turmeric powder": ("Turmeric Powder", "Dry Snacks", "Powder"),
    "haldi": ("Haldi (Turmeric Powder)", "Dry Snacks", "Powder"),
    "हल्दी": ("हल्दी", "Dry Snacks", "Powder"),
    "red chilli powder": ("Red Chilli Powder", "Dry Snacks", "Powder"),
    "lal mirch": ("Lal Mirch Powder", "Dry Snacks", "Powder"),
    "coriander powder": ("Coriander Powder", "Dry Snacks", "Powder"),
    "cumin powder": ("Cumin Powder", "Dry Snacks", "Powder"),
    "jeera powder": ("Jeera Powder", "Dry Snacks", "Powder"),
    "garam masala": ("Garam Masala", "Dry Snacks", "Powder"),
    "masala": ("Masala Powder", "Dry Snacks", "Powder"),
    "मसाला": ("मसाला", "Dry Snacks", "Powder"),
    "sugar": ("Sugar", "Dry Snacks", "Powder"),
    "चीनी": ("चीनी", "Dry Snacks", "Powder"),
    "salt": ("Salt", "Dry Snacks", "Powder"),
    "namak": ("Namak (Salt)", "Dry Snacks", "Powder"),
    "नमक": ("नमक", "Dry Snacks", "Powder"),
    "coffee powder": ("Coffee Powder", "Dry Snacks", "Powder"),
    "tea powder": ("Tea Powder", "Dry Snacks", "Powder"),
    "milk powder": ("Milk Powder", "Dry Snacks", "Powder"),
    "cocoa powder": ("Cocoa Powder", "Dry Snacks", "Powder"),
    # Tamil
    "arisi maavu": ("Arisi Maavu (Rice Flour)", "Dry Snacks", "Powder"),
    "மஞ்சள் பொடி": ("Manjal Podi (Turmeric)", "Dry Snacks", "Powder"),
    # Telugu
    "pindi": ("Pindi (Flour)", "Dry Snacks", "Powder"),
    "పసుపు": ("Pasupu (Turmeric)", "Dry Snacks", "Powder"),

    # ─── DRY SNACKS — WHOLE ──────────────────────────────────────────────────
    "namkeen": ("Namkeen", "Dry Snacks", "Whole"),
    "chips": ("Chips", "Dry Snacks", "Whole"),
    "biscuit": ("Biscuit", "Dry Snacks", "Whole"),
    "cookie": ("Cookie", "Dry Snacks", "Whole"),
    "peanuts": ("Peanuts", "Dry Snacks", "Whole"),
    "groundnut": ("Groundnut", "Dry Snacks", "Whole"),
    "mungfali": ("Mungfali (Peanuts)", "Dry Snacks", "Whole"),
    "मूंगफली": ("मूंगफली", "Dry Snacks", "Whole"),
    "cashew": ("Cashew", "Dry Snacks", "Whole"),
    "kaju": ("Kaju (Cashew)", "Dry Snacks", "Whole"),
    "काजू": ("काजू", "Dry Snacks", "Whole"),
    "almond": ("Almond", "Dry Snacks", "Whole"),
    "badam": ("Badam (Almond)", "Dry Snacks", "Whole"),
    "बादाम": ("बादाम", "Dry Snacks", "Whole"),
    "rice": ("Rice", "Dry Snacks", "Whole"),
    "chawal": ("Chawal (Rice)", "Dry Snacks", "Whole"),
    "चावल": ("चावल", "Dry Snacks", "Whole"),
    "wheat": ("Wheat", "Dry Snacks", "Whole"),
    "gehun": ("Gehun (Wheat)", "Dry Snacks", "Whole"),
    "गेहूं": ("गेहूं", "Dry Snacks", "Whole"),
    "dal": ("Dal (Lentils)", "Dry Snacks", "Whole"),
    "दाल": ("दाल", "Dry Snacks", "Whole"),
    "chana": ("Chana (Chickpeas)", "Dry Snacks", "Whole"),
    "चना": ("चना", "Dry Snacks", "Whole"),
    "moong": ("Moong Dal", "Dry Snacks", "Whole"),
    "मूंग": ("मूंग", "Dry Snacks", "Whole"),
    "popcorn": ("Popcorn", "Dry Snacks", "Whole"),
    "poha": ("Poha (Flattened Rice)", "Dry Snacks", "Whole"),
    "पोहा": ("पोहा", "Dry Snacks", "Whole"),
    "murmura": ("Murmura (Puffed Rice)", "Dry Snacks", "Whole"),
    "mathri": ("Mathri", "Dry Snacks", "Whole"),
    "sev": ("Sev", "Dry Snacks", "Whole"),
    "bhujia": ("Bhujia", "Dry Snacks", "Whole"),
    "mixture": ("Mixture Namkeen", "Dry Snacks", "Whole"),
    # Tamil
    "arisi": ("Arisi (Rice)", "Dry Snacks", "Whole"),
    "அரிசி": ("அரிசி", "Dry Snacks", "Whole"),
    "paruppu": ("Paruppu (Dal)", "Dry Snacks", "Whole"),
    "பருப்பு": ("பருப்பு", "Dry Snacks", "Whole"),
    # Telugu
    "biyyam": ("Biyyam (Rice)", "Dry Snacks", "Whole"),
    "బియ్యం": ("బియ్యం", "Dry Snacks", "Whole"),
    "pesalu": ("Pesalu (Moong Dal)", "Dry Snacks", "Whole"),
    # Bengali
    "chal": ("Chal (Rice)", "Dry Snacks", "Whole"),
    "চাল": ("চাল", "Dry Snacks", "Whole"),
    # Gujarati
    "chaval": ("Chaval (Rice)", "Dry Snacks", "Whole"),
    "ચોખા": ("ચોખા", "Dry Snacks", "Whole"),
    # Kannada
    "akki": ("Akki (Rice)", "Dry Snacks", "Whole"),
    "ಅಕ್ಕಿ": ("ಅಕ್ಕಿ", "Dry Snacks", "Whole"),
    # Punjabi
    "chawal": ("Chawal (Rice)", "Dry Snacks", "Whole"),
    "ਚਾਵਲ": ("ਚਾਵਲ", "Dry Snacks", "Whole"),

    # ─── MEAT — WHOLE ────────────────────────────────────────────────────────
    "chicken": ("Chicken", "Meat", "Whole"),
    "murgi": ("Murgi (Chicken)", "Meat", "Whole"),
    "मुर्गी": ("मुर्गी", "Meat", "Whole"),
    "fish": ("Fish", "Meat", "Whole"),
    "machli": ("Machli (Fish)", "Meat", "Whole"),
    "मछली": ("मछली", "Meat", "Whole"),
    "mutton": ("Mutton", "Meat", "Whole"),
    "bakri ka gosht": ("Mutton", "Meat", "Whole"),
    "egg": ("Egg", "Meat", "Whole"),
    "anda": ("Anda (Egg)", "Meat", "Whole"),
    "अंडा": ("अंडा", "Meat", "Whole"),
    "prawn": ("Prawn / Shrimp", "Meat", "Whole"),
    "crab": ("Crab", "Meat", "Whole"),
    "pork": ("Pork", "Meat", "Whole"),
    "beef": ("Beef", "Meat", "Whole"),
    # Tamil
    "kozhi": ("Kozhi (Chicken)", "Meat", "Whole"),
    "கோழி": ("கோழி", "Meat", "Whole"),
    "meen": ("Meen (Fish)", "Meat", "Whole"),
    "மீன்": ("மீன்", "Meat", "Whole"),
    "iraali": ("Iraali (Prawn)", "Meat", "Whole"),
    # Telugu
    "kodi": ("Kodi (Chicken)", "Meat", "Whole"),
    "కోడి": ("కోడి", "Meat", "Whole"),
    "chepa": ("Chepa (Fish)", "Meat", "Whole"),
    "చేప": ("చేప", "Meat", "Whole"),
    # Bengali
    "murgi": ("Murgi (Chicken)", "Meat", "Whole"),
    "মুরগি": ("মুরগি", "Meat", "Whole"),
    "mach": ("Mach (Fish)", "Meat", "Whole"),
    "মাছ": ("মাছ", "Meat", "Whole"),
    # Kannada
    "koli": ("Koli (Chicken)", "Meat", "Whole"),
    "ಕೋಳಿ": ("ಕೋಳಿ", "Meat", "Whole"),
    "meenu": ("Meenu (Fish)", "Meat", "Whole"),
    "ಮೀನು": ("ಮೀನು", "Meat", "Whole"),
    # Punjabi
    "murga": ("Murga (Chicken)", "Meat", "Whole"),
    "ਮੁਰਗਾ": ("ਮੁਰਗਾ", "Meat", "Whole"),
    "macchi": ("Macchi (Fish)", "Meat", "Whole"),
    "ਮੱਛੀ": ("ਮੱਛੀ", "Meat", "Whole"),

    # ─── MEAT — CUT/PROCESSED ────────────────────────────────────────────────
    "chicken pieces": ("Chicken Pieces", "Meat", "Cut/Processed"),
    "boneless chicken": ("Boneless Chicken", "Meat", "Cut/Processed"),
    "fish fillet": ("Fish Fillet", "Meat", "Cut/Processed"),
    "minced meat": ("Minced Meat / Keema", "Meat", "Cut/Processed"),
    "keema": ("Keema (Minced Meat)", "Meat", "Cut/Processed"),
    "कीमा": ("कीमा", "Meat", "Cut/Processed"),
    "kebab": ("Kebab", "Meat", "Cut/Processed"),
    "sausage": ("Sausage", "Meat", "Cut/Processed"),
    "marinated chicken": ("Marinated Chicken", "Meat", "Cut/Processed"),
    "tikka": ("Tikka (Marinated Meat)", "Meat", "Cut/Processed"),
}
